In [1]:
import numpy as np

#### 1) write a numpy program to convert ferenheit degree to centigrade degree. Frenheit values are stored in numpy array

In [7]:
f_values = np.array([32, 68, 77, 104, 212])

def f_to_c(f):
    centi = []
    for i in f:
        centi.append((i-32)*5/9)
    np.array(centi)
    return centi

c_values = f_to_c(f_values)
print(c_values)

[0.0, 20.0, 25.0, 40.0, 100.0]


In [8]:
f_values = np.array([32, 68, 77, 104, 212])
c_values = (f_values - 32) * 5/9

print(f_values)
print(c_values)

[ 32  68  77 104 212]
[  0.  20.  25.  40. 100.]


#### 2) write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements

In [16]:
arr1 = np.random.randint(0, 1000, 1000)

print(f"Average: {np.average(arr1)}")
print(f"Variance: {np.var(arr1)}")
print(f"Standard Deviation: {np.std(arr1)}")

Average: 502.733
Variance: 86115.837711
Standard Deviation: 293.4550011688334


#### 3) Write a numpy program to convert angles from degrees to radians for all elements in a given array

In [23]:
degrees = np.array([0, 30, 45, 60, 90, 120, 180, 270, 360])
radians = degrees * np.pi/180

print("Degrees: ", degrees)
print("Radians: ", radians)

Degrees:  [  0  30  45  60  90 120 180 270 360]
Radians:  [0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265 4.71238898 6.28318531]


#### 4) Write a NumPy program to calculate the difference between neighbouring elements, element-wise of a given array

In [25]:
arr2 = np.random.randint(0, 100, 10)

print(arr2)
print(np.diff(arr2))

[ 8 58 32 91  9 26 23 25 31 13]
[ 50 -26  59 -82  17  -3   2   6 -18]


#### 5) Write a numpy program to sort a given complex array using the real part first, then imaginary part.

In [70]:
real_part = np.random.randint(0, 100, 10)
img_part = np.random.randint(0, 100, 10)

complex = real_part + 1j * img_part

print("Original: ", complex)
print("Sorted: ", np.sort_complex(complex))

Original:  [16.+51.j 55.+93.j 79.+81.j 93.+47.j 15.+46.j  7.+60.j 96.+94.j 75.+31.j
 27.+35.j 66.+24.j]
Sorted:  [ 7.+60.j 15.+46.j 16.+51.j 27.+35.j 55.+93.j 66.+24.j 75.+31.j 79.+81.j
 93.+47.j 96.+94.j]


#### 6) Write a NumPy program to create a 1D array with random numbers and print the values greater than 4

In [48]:
arr3 = np.random.randint(0, 10, 10)
print(arr3)
print(arr3[arr3>4])

[9 8 3 7 9 1 0 2 2 4]
[9 8 7 9]


#### 7. Write a numpy program to create a 1D array with random numbers and search a particular number given by the user

In [71]:
arr4 = np.random.randint(1, 100, 10)
print(arr4)
num = int(input("Enter a number: "))
print(np.where(arr4==num))

[96 65 90 99 73  5 12 41 44 76]


Enter a number:  99


(array([3], dtype=int64),)


#### 8. Write a NumPy program to save a given array to a text file and load it

In [57]:
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

np.savetxt("array_data.txt", arr, fmt='%d')
print("Array saved to 'array_data.txt'.")

loaded_arr = np.loadtxt("array_data.txt", dtype=int)
print("Loaded array:", loaded_arr)

Original array: [10 20 30 40 50]
Array saved to 'array_data.txt'.
Loaded array: [10 20 30 40 50]


In [58]:
arr = np.array([5, 10, 15, 20, 25])
print("Original array:", arr)

with open("my_array.txt", "w") as f:
    for item in arr:
        f.write(f"{item}\n")

print("Array saved to 'my_array.txt' using file handling.")

loaded_list = []
with open("my_array.txt", "r") as f:
    for line in f:
        loaded_list.append(int(line.strip()))

loaded_arr = np.array(loaded_list)
print("Loaded array:", loaded_arr)

Original array: [ 5 10 15 20 25]
Array saved to 'my_array.txt' using file handling.
Loaded array: [ 5 10 15 20 25]


#### 9) Write a NumPy program to create an array of all the even integers from 30 to 60

In [59]:
even_arr = np.arange(30, 61, 2)
print(even_arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


#### 10) Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [66]:
arr = np.array([[10, 20, 30, 40],[5, 15, 25, 35]])
print("Sum of all elements: ", arr.sum())
print("Sum of each column: ", arr.sum(axis=0))
print("Sum of each row: ", arr.sum(axis=1))

Sum of all elements:  180
Sum of each column:  [15 35 55 75]
Sum of each row:  [100  80]
