In [42]:
import numpy as np
import scipy as sp

In [ ]:
arr1=(1,2,3,4,5)
arr1_p=np.array(arr1)
print(arr1_p)

[1 2 3 4 5]


In [ ]:
print(arr1.dtype)
print(type(arr1))

int32
<class 'numpy.ndarray'>


In [ ]:
b=np.array([4,5,6])


In [6]:
c=np.arange(100,200,5)
c

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [9]:
d=np.zeros((3,4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
d=np.ones((3,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
ey=np.eye(3)
ey

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
arr3 = np.arange(1,10)
print(arr3)
print(arr3[2:5])
print(arr3[-2:-5:-1])

[1 2 3 4 5 6 7 8 9]
[3 4 5]
[8 7 6]


In [22]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
arr4_cpy=np.copy(arr3)
print(arr4_cpy)

[1 2 3 4 5 6 7 8 9]


In [33]:
arr3_copy = arr3[:]
print(arr3_copy)

[1 2 3 4 5 6 7 8 9]


In [37]:
arr3_copy = np.array([2, 3,4 ,5,6])
print(arr3_copy)

[2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a, b))
print(c)

[1 2 3 3 5 6]


In [53]:
matrix1= np.array([[1, 2, 3], [4, 5, 6]])
matrix2= np.array([[7, 8, 9], [10, 11, 12]])
matrix3 = np.concatenate((matrix1, matrix2), axis=1)
print(matrix3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [66]:
find_element=np.where(arr3==4)
print(find_element)

if find_element[0].size > 0:
    print(f"4 is present in the array location  {find_element[0][0]}")
else:
    print("4 is not present in the array")



(array([3], dtype=int64),)
4 is present in the array location  3
